const ActionTypes = {
    FOUND_STOPS: 'FOUND_STOPS',
    USER_POSITION_LOADED: 'USER_POSITION_LOADED',
    USER_LOCATION_LOADED: 'USER_LOCATION_LOADED',
    START_LOCATION_INPUT_CHANGED: 'START_LOCATION_INPUT_CHANGED',
    DESTINATION_LOCATION_INPUT_CHANGED: 'DESTINATION_LOCATION_INPUT_CHANGED',
    SHOW_LOADING: 'SHOW_LOADING',
    CITIES_LOADED: 'CITIES_LOADED',
    SELECT_CITY: 'SELECT_CITY',
    SHOW_CITIES_MODAL: 'SHOW_CITIES_MODAL',
    SWAP_SEARCH_VALUES: 'SWAP_SEARCH_VALUES',
    SHOW_DIRECTION: 'SHOW_DIRECTION',
    FIRST_GEOLOCATION_DONE: 'FIRST_GEOLOCATION_DONE',
    SHOW_DEPARTURES_MENU: 'SHOW_DEPARTURES_MENU',
    SET_DEPARTURES_START_STOP: 'SET_DEPARTURES_START_STOP',
    SET_DEPARTURES_DESTINATION_STOP: 'SET_DEPARTURES_DESTINATION_STOP',
    SET_DEPARTURES_TIME: 'SET_DEPARTURES_TIME',
    FOUND_DEPARTURES: 'FOUND_DEPARTURES',
    CHANGE_DEPARTURES_SELECTED_STOP: 'CHANGE_DEPARTURES_SELECTED_STOP',
    SHOW_TIME_MODAL: 'SHOW_TIME_MODAL',
};

export default ActionTypes;