export const actionTypes = {
	FOUND_STOPS: 						'FOUND_STOPS',
	USER_POSITION_LOADED: 				'USER_POSITION_LOADED',
	USER_LOCATION_LOADED: 				'USER_LOCATION_LOADED',
	START_LOCATION_INPUT_CHANGED: 		'START_LOCATION_INPUT_CHANGED',
  	DESTINATION_LOCATION_INPUT_CHANGED: 'DESTINATION_LOCATION_INPUT_CHANGED',
  	SHOW_LOADING: 						'SHOW_LOADING',
};