export const actionTypes = {
	FOUND_STOPS: 						'FOUND_STOPS',
	USER_POSITION_LOADED: 				'USER_POSITION_LOADED',
	USER_LOCATION_LOADED: 				'USER_LOCATION_LOADED',
	CURRENT_LOCATION_INPUT_CHANGED: 	'CURRENT_LOCATION_INPUT_CHANGED',
  	DESTINATION_LOCATION_INPUT_CHANGED: 'DESTINATION_LOCATION_INPUT_CHANGED'
};